version: "3.3"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: starshop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mount the init.sql file
  # ----------------- Doesn't work --------------------------------
  # springboot:
  #   build: .
  #   ports:
  #     - "9090:9090"
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/starshop
  #     SPRING_DATASOURCE_USERNAME: user
  #     SPRING_DATASOURCE_PASSWORD: password
  #   restart: always
volumes:
  mysql_data:
